[build]
  command = "yarn run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "10.15.3"


[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy= "no-referrer-when-downgrade"


# social media card assets
[[redirects]]
  from = "/card-image/:path"
  to = "https://hawksworx-cards.netlify.com/card/www-hawksworx-com:path"
  status = 302


# Simplify requests for my headshots
[[redirects]]
  from = "/philhawksworth-*"
  to = "/images/philhawksworth-:splat"

# Look after the old use of journal in urls
[[redirects]]
  from = "/journal/*"
  to = "/blog/:splat"
  status = 301

# Simplified blog urls for slugs
[[redirects]]
  from = "/blog/:year/:month/:day/:slug"
  to = "/blog/:slug"
  status = 301

# 404s
[[redirects]]
  from = "*"
  to = "/404"
  status = 404


# Config for the Netlify Build Plugin: netlify-plugin-minify-html
[[plugins]]
  package = "netlify-plugin-minify-html"

  # Specify which deploy contexts we'll minify HTML in.
  # Supports any Deploy Contexts available in Netlify.
  # https://docs.netlify.com/site-deploys/overview/#deploy-contexts
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]

  # Override the default options for the minification
  # https://github.com/kangax/html-minifier#options-quick-reference
  [plugins.inputs.minifierOptions]
    removeComments = true
    collapseInlineTagWhitespace = false
